version: '3.7'
services:

  config:
    environment:
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}${CONFIG_SERVICE_DEV_DEBUG_PORT}
    build: config
    ports:
      - $CONFIG_SERVICE_DEV_PORT:$CONFIG_SERVICE_DEV_PORT
      - $CONFIG_SERVICE_DEV_DEBUG_PORT:$CONFIG_SERVICE_DEV_DEBUG_PORT

  registry:
    environment:
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}${REGISTRY_SERVICE_DEV_DEBUG_PORT}
    build: registry
    ports:
      - $REGISTRY_SERVICE_DEV_PORT:$REGISTRY_SERVICE_DEV_PORT
      - $REGISTRY_SERVICE_DEV_DEBUG_PORT:$REGISTRY_SERVICE_DEV_DEBUG_PORT

  account-gateway:
    environment:
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}${ACCOUNT_GATEWAY_DEV_DEBUG_PORT}
    build: account-gateway
    ports:
      - $ACCOUNT_GATEWAY_DEV_PORT:$ACCOUNT_GATEWAY_DEV_PORT
      - $ACCOUNT_GATEWAY_DEV_DEBUG_PORT:$ACCOUNT_GATEWAY_DEV_DEBUG_PORT

  account-auth:
    environment:
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}${ACCOUNT_AUTH_DEV_DEBUG_PORT}
    build: account-auth
    ports:
      - $ACCOUNT_AUTH_DEV_PORT:$ACCOUNT_AUTH_DEV_PORT
      - $ACCOUNT_AUTH_DEV_DEBUG_PORT:$ACCOUNT_AUTH_DEV_DEBUG_PORT

  account-auth-mysqld:
    build: mysqld
    ports:
      - $ACCOUNT_AUTH_MYSQLDB_EXTERNAL_DEV_PORT:$MYSQLDB_SERVICE_INTERNAL_DEV_PORT

  account-service:
    environment:
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}${ACCOUNT_SERVICE_DEV_DEBUG_PORT}
    build: account-service
    ports:
      - $ACCOUNT_SERVICE_DEV_PORT:$ACCOUNT_SERVICE_DEV_PORT
      - $ACCOUNT_SERVICE_DEV_DEBUG_PORT:$ACCOUNT_SERVICE_DEV_DEBUG_PORT

  consumer-gateway:
    environment:
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}${CONSUMER_GATEWAY_DEV_DEBUG_PORT}
    build: consumer-gateway
    ports:
      - $CONSUMER_GATEWAY_DEV_PORT:$CONSUMER_GATEWAY_DEV_PORT
      - $CONSUMER_GATEWAY_DEV_DEBUG_PORT:$CONSUMER_GATEWAY_DEV_DEBUG_PORT

  consumer-auth:
    environment:
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}${CONSUMER_AUTH_DEV_DEBUG_PORT}
    build: consumer-auth
    ports:
      - $CONSUMER_AUTH_DEV_PORT:$CONSUMER_AUTH_DEV_PORT
      - $CONSUMER_AUTH_DEV_DEBUG_PORT:$CONSUMER_AUTH_DEV_DEBUG_PORT

  consumer-auth-mysqld:
    build: mysqld
    ports:
      - $CONSUMER_AUTH_MYSQLDB_EXTERNAL_DEV_PORT:$MYSQLDB_SERVICE_INTERNAL_DEV_PORT

  consumer-service:
    environment:
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}${CONSUMER_SERVICE_DEV_DEBUG_PORT}
    build: consumer-service
    ports:
      - $CONSUMER_SERVICE_DEV_PORT:$CONSUMER_SERVICE_DEV_PORT
      - $CONSUMER_SERVICE_DEV_DEBUG_PORT:$CONSUMER_SERVICE_DEV_DEBUG_PORT

  training-mysqld:
    build: mysqld
    ports:
      - $MYSQLDB_TRAINING_EXTERNAL_DEV_PORT:$MYSQLDB_SERVICE_INTERNAL_DEV_PORT


  rabbitmq:
    ports:
      - $RABBITMQ_SERVICE_INTERNAL_DEV_PORT:$RABBITMQ_SERVICE_INTERNAL_DEV_PORT
