version: '3.7'
services:

  config:
    environment:
      CONFIG_SERVICE_PASSWORD:             $CONFIG_SERVICE_PASSWORD
      CONFIG_SERVICE_DEV_PORT:             $CONFIG_SERVICE_DEV_PORT
      AUTH_SERVICE_DEV_PORT:               $AUTH_SERVICE_DEV_PORT
      REGISTRY_SERVICE_DEV_PORT:           $REGISTRY_SERVICE_DEV_PORT
    image: mservicet-config
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    environment:
      CONFIG_SERVICE_PASSWORD:    $CONFIG_SERVICE_PASSWORD
      CONFIG_SERVICE_DEV_PORT:    $CONFIG_SERVICE_DEV_PORT
      REGISTRY_SERVICE_DEV_PORT:  $REGISTRY_SERVICE_DEV_PORT
    image: mservicet-registry
    restart: always
    depends_on:
      - config
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway-point:
    environment:
      CONFIG_SERVICE_PASSWORD:    $CONFIG_SERVICE_PASSWORD
      CONFIG_SERVICE_DEV_PORT:    $CONFIG_SERVICE_DEV_PORT
      REGISTRY_SERVICE_DEV_PORT:  $REGISTRY_SERVICE_DEV_PORT
      AUTH_SERVICE_DEV_PORT:      $AUTH_SERVICE_DEV_PORT
      GATEWAY_SERVICE_DEV_PORT:   $GATEWAY_SERVICE_DEV_PORT
    image: mservicet-gateway-point
    restart: always
    depends_on:
      - config
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-service:
    environment:
      CONFIG_SERVICE_PASSWORD:              $CONFIG_SERVICE_PASSWORD
      CONFIG_SERVICE_DEV_PORT:              $CONFIG_SERVICE_DEV_PORT
      ACCOUNT_SERVICE_PASSWORD:             $ACCOUNT_SERVICE_PASSWORD
      SERVICE_ACCOUNT_PASSWORD:              $SERVICE_ACCOUNT_PASSWORD
      AUTH_SERVICE_DEV_PORT:                $AUTH_SERVICE_DEV_PORT
      MYSQLDB_PASSWORD:                     $MYSQLDB_PASSWORD
      REGISTRY_SERVICE_DEV_PORT:            $REGISTRY_SERVICE_DEV_PORT
      MYSQLDB_SERVICE_INTERNAL_DEV_PORT:    $MYSQLDB_SERVICE_INTERNAL_DEV_PORT
    image: mservicet-auth-service
    restart: always
    depends_on:
      - config
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-mysqld:
    image: mservicet-auth-mysqld
    environment:
      MYSQL_DATABASE: spring_social
      MYSQL_ROOT_PASSWORD: qwerty
    restart: always

  account-service:
    environment:
      CONFIG_SERVICE_PASSWORD:              $CONFIG_SERVICE_PASSWORD
      CONFIG_SERVICE_DEV_PORT:              $CONFIG_SERVICE_DEV_PORT
      ACCOUNT_SERVICE_PASSWORD:             $ACCOUNT_SERVICE_PASSWORD
      MYSQLDB_PASSWORD:                     $MYSQLDB_PASSWORD
      ACCOUNT_SERVICE_DEV_PORT:             $ACCOUNT_SERVICE_DEV_PORT
      AUTH_SERVICE_DEV_PORT:                $AUTH_SERVICE_DEV_PORT
      MYSQLDB_SERVICE_INTERNAL_DEV_PORT:    $MYSQLDB_SERVICE_INTERNAL_DEV_PORT
      REGISTRY_SERVICE_DEV_PORT:            $REGISTRY_SERVICE_DEV_PORT
    image: mservicet-account-service
    restart: always
    depends_on:
      - config
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  account-mysqld:
    environment:
      MYSQL_DATABASE: accountDB
      MYSQL_ROOT_PASSWORD: qwerty
    image: mservicet-mysqld
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  service-account:
    environment:
      CONFIG_SERVICE_PASSWORD:              $CONFIG_SERVICE_PASSWORD
      CONFIG_SERVICE_DEV_PORT:              $CONFIG_SERVICE_DEV_PORT
      SERVICE_ACCOUNT_PASSWORD:             $SERVICE_ACCOUNT_PASSWORD
      MYSQLDB_PASSWORD:                     $MYSQLDB_PASSWORD
      SERVICE_ACCOUNT_DEV_PORT:             $SERVICE_ACCOUNT_DEV_PORT
      AUTH_SERVICE_DEV_PORT:                $AUTH_SERVICE_DEV_PORT
      MYSQLDB_SERVICE_INTERNAL_DEV_PORT:    $MYSQLDB_SERVICE_INTERNAL_DEV_PORT
      REGISTRY_SERVICE_DEV_PORT:            $REGISTRY_SERVICE_DEV_PORT
    image: mservicet-service-account
    restart: always
    depends_on:
      - config
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  service-mysqld:
    environment:
      MYSQL_DATABASE: deviceDB
      MYSQL_ROOT_PASSWORD: qwerty
    image: mservicet-mysqld
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - $RABBITMQ_SERVICE_INTERNAL_PROD_PORT:$RABBITMQ_SERVICE_INTERNAL_PROD_PORT
    logging:
      options:
        max-size: "10m"
        max-file: "10"
