version: '2.1'
services:

  config:
    build: config
    ports:
      - 8888:8888

  gateway-point:
      build: gateway-point

  auth-service:
      build: auth-service
      ports:
        - 5000:5000

  auth-mongodb:
    build: mongodb
    ports:
      - 25000:27017

  registry:
    build: registry

  monitoring:
    build: monitoring


