security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:${AUTH_SERVICE_DEV_PORT}/mservicet/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://account-mysqld:${DEFAULT_MYSQL_DB_PORT}/accountDB?useUnicode=yes&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: qwerty
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: create
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  servlet:
    context-path: /accounts
  port: ${ACCOUNT_SERVICE_DEV_PORT}