logging:
  level:
    org.springframework.security: INFO

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry:${REGISTRY_SERVICE_DEV_PORT}/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:${ACCOUNT_AUTH_DEV_PORT}/mservicet/users/current

spring:
  rabbitmq:
    host: rabbitmq
