spring:
  data:
    mongodb:
      host: auth-mongodb
      username: user
      password: ${MYSQLDB_PASSWORD}
      database: mservicet
      port: ${MYSQLDB_SERVICE_INTERNAL_DEV_PORT}

server:
  servlet:
    context-path: /mservicet
  port: ${AUTH_SERVICE_DEV_PORT}
