security:
  oauth2:
    resource:
      user-info-uri: http://consumer-auth:${CONSUMER_AUTH_DEV_PORT}/mservicet/users/current
    client:
      clientId: consumer-service
      clientSecret: ${CONSUMER_SERVICE_PASSWORD}
      accessTokenUri: http://consumer-auth:${CONSUMER_AUTH_DEV_PORT}/mservicet/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://training-mysqld:${MYSQLDB_SERVICE_INTERNAL_DEV_PORT}/trainingDB?useUnicode=yes&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: qwerty
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: create
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  servlet:
    context-path: /services
  port: ${CONSUMER_SERVICE_DEV_PORT}
