hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 320000

ribbon:
  ReadTimeout: 320000
  ConnectTimeout: 320000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 320000
    socket-timeout-millis: 320000

  routes:
    auth-service:
      path: /mservicet/**
      url: http://consumer-auth:${CONSUMER_AUTH_DEV_PORT}
      stripPrefix: false
      sensitiveHeaders:

    consumer-service-1:
      path: /consumers/**
      serviceId: consumer-service
      stripPrefix: false
      sensitiveHeaders:

    consumer-service-2:
      path: /consumers/trainings/**
      serviceId: consumer-service
      stripPrefix: false
      sensitiveHeaders:

server:
  port: ${CONSUMER_GATEWAY_DEV_PORT}
