security:
  oauth2:
    client:
      clientId: service-account
      clientSecret: ${SERVICE_ACCOUNT_PASSWORD}
      accessTokenUri: http://auth-service:${AUTH_SERVICE_DEV_PORT}/mservicet/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: device-mongodb
      username: user
      password: ${MYSQLDB_PASSWORD}
      database: mservicet
      port: ${MYSQLDB_SERVICE_INTERNAL_DEV_PORT}

server:
  servlet:
    context-path: /devices
  port: ${SERVICE_ACCOUNT_DEV_PORT}
